# Generated by Django 5.1.4 on 2024-12-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('semi-public', 'Semi-public'), ('private', 'Private')], default='public', max_length=20)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
